# Generated by Django 5.1.9 on 2025-10-23 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightCode', models.CharField(max_length=10, unique=True, verbose_name='航班代碼')),
                ('airline', models.CharField(max_length=50, verbose_name='航空公司')),
                ('departureTime', models.TimeField(verbose_name='抵達時間')),
                ('arrivalTime', models.TimeField(verbose_name='出發時間')),
                ('departureAirport', models.CharField(max_length=50, verbose_name='抵達機場')),
                ('arrivalAirport', models.CharField(max_length=50, verbose_name='出發機場')),
            ],
            options={
                'verbose_name': '航班資訊',
                'verbose_name_plural': '航班資訊',
                'db_table': 'ticket_info',
                'ordering': ['departureTime'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureDate', models.DateField(verbose_name='出發日期')),
                ('arrivalDate', models.DateField(verbose_name='抵達日期')),
                ('cabinClass', models.CharField(max_length=10, verbose_name='艙等')),
                ('aircraftType', models.CharField(max_length=20, verbose_name='機型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='當前票價')),
                ('recPrice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='推薦票價')),
                ('currency', models.CharField(default='TWD', max_length=3, verbose_name='幣別')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ticket.ticket', verbose_name='航班資訊')),
            ],
            options={
                'verbose_name': '票價',
                'verbose_name_plural': '票價',
                'indexes': [models.Index(fields=['ticket', 'departureDate'], name='ticket_pric_ticket__d6310d_idx'), models.Index(fields=['departureDate'], name='ticket_pric_departu_ae6d46_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'departureDate', 'cabinClass'), name='uniq_ticket_date_cabin'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_non_negative'), models.CheckConstraint(condition=models.Q(('recPrice__gte', 0)), name='recprice_non_negative')],
            },
        ),
    ]
