# Generated by Django 5.1.9 on 2025-10-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['depTime'], 'verbose_name': '航班資訊', 'verbose_name_plural': '航班資訊'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='arrivalAirport',
            new_name='arrAirport',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='arrivalTime',
            new_name='arrTime',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='departureAirport',
            new_name='depAirport',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='departureTime',
            new_name='depTime',
        ),
        migrations.AddField(
            model_name='ticket',
            name='arrAirportCode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='出發機場代號'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='arrCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出發城市'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='depAirportCode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='抵達機場代號'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='depCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='抵達城市'),
        ),
    ]
