# Generated by Django 5.1.9 on 2025-10-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='uniq_ticket_date_cabin',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='ticket_pric_ticket__d6310d_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='ticket_pric_departu_ae6d46_idx',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='cabinClass',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='arrivalDate',
            new_name='arrDate',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='departureDate',
            new_name='depDate',
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['ticket', 'depDate'], name='ticket_pric_ticket__167f02_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['depDate'], name='ticket_pric_depDate_7b322b_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('ticket', 'depDate', 'Class'), name='uniq_ticket_date_cabin'),
        ),
    ]
