# Generated by Django 5.1.9 on 2025-10-23 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_remove_price_uniq_ticket_date_cabin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineCode', models.CharField(max_length=3, unique=True, verbose_name='航空公司代碼')),
                ('airlineName', models.CharField(max_length=100, verbose_name='航空公司名稱')),
                ('country', models.CharField(max_length=50, verbose_name='國家')),
                ('hubAirport', models.CharField(max_length=50, verbose_name='主要樞紐機場')),
                ('alliance', models.CharField(blank=True, max_length=30, null=True, verbose_name='聯盟')),
                ('foundedYear', models.IntegerField(blank=True, null=True, verbose_name='成立年份')),
                ('website', models.URLField(blank=True, null=True, verbose_name='官網')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/', verbose_name='公司標誌')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='airlineinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.airline', verbose_name='航空公司資訊'),
        ),
    ]
