# Generated by Django 5.1.9 on 2025-10-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_airline_ticket_airlineinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'ordering': ['airlineCode'], 'verbose_name': '航空公司資訊', 'verbose_name_plural': '航空公司資訊'},
        ),
        migrations.AlterModelTable(
            name='airline',
            table='airline_info',
        ),
    ]
