# Generated by Django 5.1.9 on 2025-10-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_airline_options_alter_airline_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='arrAirport',
            field=models.CharField(max_length=50, verbose_name='抵達機場'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrAirportCode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='抵達機場代號'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='抵達城市'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='arrTime',
            field=models.TimeField(verbose_name='抵達時間'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depAirport',
            field=models.CharField(max_length=50, verbose_name='出發機場'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depAirportCode',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='出發機場代號'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depCity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出發城市'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='depTime',
            field=models.TimeField(verbose_name='出發時間'),
        ),
    ]
